### ISSUE TITLE
Add CSS var to control marker character

### ISSUE THREAD

**Issue by joshuabaker** [joshuabaker/lists-css#1]
Using a CSS var for the `content` value would allow customisation.

```css
.bulleted-list > li:before {
  content: var(--list-marker-char, "—");
}
```

**Example**

```css
:root {
  --list-marker-char: "→";
}
```
